In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Carga desde un archivo.csv sin indice
data = pd.read_csv('Ventas_totales.csv')
data

,indice_tiempo,ventas_precios_corrientes,ventas_precios_constantes,ventas_totales_canal_venta,salon_ventas,canales_on_line,ventas_totales_medio_pago,efectivo,tarjetas_debito,tarjetas_credito,...,almacen,panaderia,lacteos,carnes,verduleria_fruteria,alimentos_preparados_rotiseria,articulos_limpieza_perfumeria,indumentaria_calzado_textiles_hogar,electronicos_articulos_hogar,otros
0,01/01/2017,27858.9,27477.3,2.785887e+07,2.759173e+07,2.671420e+05,2.785887e+07,1.023010e+07,6.864575e+06,9.047205e+06,...,6.705475e+06,9.459063e+05,2.880656e+06,2.606193e+06,1.050314e+06,3.407774e+05,4.397544e+06,7.723718e+05,1.838507e+06,2.806660e+06
1,01/02/2017,25994.2,25223.4,2.599420e+07,2.574918e+07,2.450208e+05,2.599420e+07,9.719067e+06,6.438494e+06,8.309150e+06,...,6.576625e+06,9.256186e+05,2.855640e+06,2.600084e+06,1.026167e+06,3.282887e+05,4.053284e+06,6.722905e+05,1.257662e+06,2.354085e+06
2,01/03/2017,27780.0,26334.3,2.778001e+07,2.747223e+07,3.077778e+05,2.778001e+07,1.024444e+07,6.908523e+06,8.845010e+06,...,7.437264e+06,1.016148e+06,3.188259e+06,2.824977e+06,1.075526e+06,3.533352e+05,4.354198e+06,6.676967e+05,1.305675e+06,2.266189e+06
3,01/04/2017,29134.3,27045.9,2.913427e+07,2.882748e+07,3.067927e+05,2.913427e+07,1.031263e+07,7.454252e+06,9.458167e+06,...,8.211244e+06,1.132396e+06,3.257140e+06,3.006159e+06,1.037213e+06,3.596945e+05,4.355707e+06,8.389482e+05,1.535726e+06,2.146756e+06
4,01/05/2017,27969.0,25631.9,2.796900e+07,2.756931e+07,3.996933e+05,2.796900e+07,1.014761e+07,6.735747e+06,9.220930e+06,...,7.651058e+06,1.033082e+06,3.232636e+06,2.799142e+06,9.826512e+05,3.365680e+05,4.206102e+06,9.158951e+05,1.824462e+06,2.117971e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,01/01/2022,154517.1,45463.4,1.545171e+08,1.496976e+08,4.819480e+06,1.545171e+08,4.696260e+07,4.605365e+07,5.404833e+07,...,3.750517e+07,4.860318e+06,1.610477e+07,1.740849e+07,6.138441e+06,1.401929e+06,2.133021e+07,3.782646e+06,1.218755e+07,1.343307e+07
61,01/02/2022,152202.6,23802.1,1.522026e+08,1.484065e+08,3.796044e+06,1.522026e+08,4.629096e+07,4.528358e+07,5.370589e+07,...,3.820979e+07,5.045920e+06,1.613982e+07,1.826074e+07,6.436028e+06,1.370640e+06,2.030545e+07,NaN,9.189746e+06,1.330139e+07
62,01/03/2022,16.5,24612.4,1.689825e+08,1.643211e+08,4.661350e+05,1.689825e+08,5.126208e+07,4.736436e+07,NaN,...,4.541886e+07,5.922820e+06,1.841916e+07,2.082760e+07,6.886240e+06,1.589119e+06,2.294201e+07,3.912852e+06,1.089879e+07,NaN
63,01/04/2022,177148.1,24140.5,1.771481e+08,1.730038e+08,4.144284e+06,1.771481e+08,5.319000e+07,5.006397e+07,6.535759e+07,...,4.999168e+07,6.746167e+06,1.930946e+07,2.287784e+07,6.510666e+06,1.719459e+06,2.313127e+07,4.228054e+06,NaN,1.191048e+07
64,01/05/2022,179639.2,23234.2,1.796392e+08,1.753585e+08,4.280751e+06,1.796392e+08,5.273811e+07,4.988679e+07,6.807009e+07,...,5.015035e+07,6.667330e+06,2.012112e+07,2.284153e+07,6.314109e+06,1.779483e+06,2.357864e+07,5.213153e+06,1.203960e+07,1.234998e+07

In [15]:
# Identificar valores nulos por columna
valores_nulos = data.isnull().sum()
valores_nulos

indice_tiempo                           0
ventas_precios_corrientes               0
ventas_precios_constantes               0
ventas_totales_canal_venta              0
salon_ventas                            6
canales_on_line                         0
ventas_totales_medio_pago               0
efectivo                                0
tarjetas_debito                         1
tarjetas_credito                        7
otros_medios                            1
ventas_totales_grupo_articulos          0
subtotal_ventas_alimentos_bebidas      10
bebidas                                 1
almacen                                 2
panaderia                               1
lacteos                                 1
carnes                                  1
verduleria_fruteria                     1
alimentos_preparados_rotiseria          1
articulos_limpieza_perfumeria           0
indumentaria_calzado_textiles_hogar     2
electronicos_articulos_hogar            3
otros                                   4
dtype: int64

In [16]:
# Identificar valores nulos por dataframe
valores_nulos = data.isnull().sum().sum()
valores_nulos

np.int64(42)

In [4]:
# Realizamos una copia del dataframe
data1 = data.copy()

MÉTODOS DE SUSTITUCIÓN DE VALORES NULOS

Primer método de sustitución de valores nulos

Sustituir valores nulos con promedio o media

In [5]:
data1["salon_ventas"] = data1["salon_ventas"].fillna(round(data["salon_ventas"].mean(),1))
data1["subtotal_ventas_alimentos_bebidas"] = data1["subtotal_ventas_alimentos_bebidas"].fillna(round(data["subtotal_ventas_alimentos_bebidas"].mean(),1))
data1["otros"] = data1["otros"].fillna(round(data["otros"].mean(),1))

# Identificar valores nulos por columna
valores_nulos = data1.isnull().sum()
valores_nulos

indice_tiempo                          0
ventas_precios_corrientes              0
ventas_precios_constantes              0
ventas_totales_canal_venta             0
salon_ventas                           0
canales_on_line                        0
ventas_totales_medio_pago              0
efectivo                               0
tarjetas_debito                        1
tarjetas_credito                       7
otros_medios                           1
ventas_totales_grupo_articulos         0
subtotal_ventas_alimentos_bebidas      0
bebidas                                1
almacen                                2
panaderia                              1
lacteos                                1
carnes                                 1
verduleria_fruteria                    1
alimentos_preparados_rotiseria         1
articulos_limpieza_perfumeria          0
indumentaria_calzado_textiles_hogar    2
electronicos_articulos_hogar           3
otros                                  0
dtype: int64

In [19]:
# Convertir dataframe a csv
data1.to_csv("Metodo1.csv")

Segundo método de sustitución de valores nulo

Sustituir valores nulos con mediana

In [20]:
data1["tarjetas_debito"] = data1["tarjetas_debito"].fillna(round(data["tarjetas_debito"].median(),1))
data1["tarjetas_credito"] = data1["tarjetas_credito"].fillna(round(data["tarjetas_credito"].median(),1))
data1["otros_medios"] = data1["otros_medios"].fillna(round(data["otros_medios"].median(),1))

# Identificar valores nulos por columna
valores_nulos = data1.isnull().sum()
valores_nulos

indice_tiempo                          0
ventas_precios_corrientes              0
ventas_precios_constantes              0
ventas_totales_canal_venta             0
salon_ventas                           0
canales_on_line                        0
ventas_totales_medio_pago              0
efectivo                               0
tarjetas_debito                        0
tarjetas_credito                       0
otros_medios                           0
ventas_totales_grupo_articulos         0
subtotal_ventas_alimentos_bebidas      0
bebidas                                1
almacen                                2
panaderia                              1
lacteos                                1
carnes                                 1
verduleria_fruteria                    1
alimentos_preparados_rotiseria         1
articulos_limpieza_perfumeria          0
indumentaria_calzado_textiles_hogar    2
electronicos_articulos_hogar           3
otros                                  0
dtype: int64

In [21]:
# Convertir dataframe a csv
data1.to_csv("Metodo2.csv")

Tercer método de sustitución de valores nulos 

Sustituir valores nulos por un valor númerico en concreto

In [22]:
data1["panaderia"] = data1["panaderia"].fillna(1)
data1["carnes"] = data1["carnes"].fillna(1)
data1["verduleria_fruteria"] = data1["verduleria_fruteria"].fillna(1)

# Identificar valores nulos por columna
valores_nulos = data1.isnull().sum()
valores_nulos

indice_tiempo                          0
ventas_precios_corrientes              0
ventas_precios_constantes              0
ventas_totales_canal_venta             0
salon_ventas                           0
canales_on_line                        0
ventas_totales_medio_pago              0
efectivo                               0
tarjetas_debito                        0
tarjetas_credito                       0
otros_medios                           0
ventas_totales_grupo_articulos         0
subtotal_ventas_alimentos_bebidas      0
bebidas                                1
almacen                                2
panaderia                              0
lacteos                                1
carnes                                 0
verduleria_fruteria                    0
alimentos_preparados_rotiseria         1
articulos_limpieza_perfumeria          0
indumentaria_calzado_textiles_hogar    2
electronicos_articulos_hogar           3
otros                                  0
dtype: int64

In [23]:
# Convertir dataframe a csv
data1.to_csv("Metodo3.csv")

Cuarto método de sustitución de valores nulos 

Sustituir valores nulos por un string en concreto

In [24]:
data1["indumentaria_calzado_textiles_hogar"] = data1["indumentaria_calzado_textiles_hogar"].fillna("111111")
data1["electronicos_articulos_hogar"] = data1["electronicos_articulos_hogar"].fillna("111111")

# Corroboramos datos nulos
valores_nulos=data1.isnull().sum()
valores_nulos

indice_tiempo                          0
ventas_precios_corrientes              0
ventas_precios_constantes              0
ventas_totales_canal_venta             0
salon_ventas                           0
canales_on_line                        0
ventas_totales_medio_pago              0
efectivo                               0
tarjetas_debito                        0
tarjetas_credito                       0
otros_medios                           0
ventas_totales_grupo_articulos         0
subtotal_ventas_alimentos_bebidas      0
bebidas                                1
almacen                                2
panaderia                              0
lacteos                                1
carnes                                 0
verduleria_fruteria                    0
alimentos_preparados_rotiseria         1
articulos_limpieza_perfumeria          0
indumentaria_calzado_textiles_hogar    0
electronicos_articulos_hogar           0
otros                                  0
dtype: int64

In [25]:
# Convertir dataframe a csv
data1.to_csv("Metodo4.csv")

Quinto método de sustitución de valores nulos

Sustituir valores nulos por valores no nulos hacia adelante "forward fill"

In [26]:
# Filtro por columnas
data1["bebidas"] = data1["bebidas"].fillna(method = "ffill")
data1["almacen"] = data1["almacen"].fillna(method = "ffill")

# Corroboramos datos nulos
valores_nulos=data1.isnull().sum()
valores_nulos

C:\Users\yulia\AppData\Local\Temp\ipykernel_14668\2181983249.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data1["bebidas"] = data1["bebidas"].fillna(method = "ffill")
C:\Users\yulia\AppData\Local\Temp\ipykernel_14668\2181983249.py:3: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data1["almacen"] = data1["almacen"].fillna(method = "ffill")

indice_tiempo                          0
ventas_precios_corrientes              0
ventas_precios_constantes              0
ventas_totales_canal_venta             0
salon_ventas                           0
canales_on_line                        0
ventas_totales_medio_pago              0
efectivo                               0
tarjetas_debito                        0
tarjetas_credito                       0
otros_medios                           0
ventas_totales_grupo_articulos         0
subtotal_ventas_alimentos_bebidas      0
bebidas                                0
almacen                                0
panaderia                              0
lacteos                                1
carnes                                 0
verduleria_fruteria                    0
alimentos_preparados_rotiseria         1
articulos_limpieza_perfumeria          0
indumentaria_calzado_textiles_hogar    0
electronicos_articulos_hogar           0
otros                                  0
dtype: int64

In [27]:
# Convertir dataframe a csv
data1.to_csv("Metodo5.csv")

Sexto método de sustitución de valores nulos 

Sustituir valores nulos no nulos hacia atrás backward fill ("bfill")

In [28]:
# Filtro por columnas
data1["lacteos"] = data1["lacteos"].fillna(method = "bfill")
data1["alimentos_preparados_rotiseria"] = data1["alimentos_preparados_rotiseria"].fillna(method = "bfill")

# Corroboramos datos nulos
valores_nulos = data1.isnull().sum()
valores_nulos

C:\Users\yulia\AppData\Local\Temp\ipykernel_14668\4119798367.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data1["lacteos"] = data1["lacteos"].fillna(method = "bfill")
C:\Users\yulia\AppData\Local\Temp\ipykernel_14668\4119798367.py:3: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data1["alimentos_preparados_rotiseria"] = data1["alimentos_preparados_rotiseria"].fillna(method = "bfill")

indice_tiempo                          0
ventas_precios_corrientes              0
ventas_precios_constantes              0
ventas_totales_canal_venta             0
salon_ventas                           0
canales_on_line                        0
ventas_totales_medio_pago              0
efectivo                               0
tarjetas_debito                        0
tarjetas_credito                       0
otros_medios                           0
ventas_totales_grupo_articulos         0
subtotal_ventas_alimentos_bebidas      0
bebidas                                0
almacen                                0
panaderia                              0
lacteos                                0
carnes                                 0
verduleria_fruteria                    0
alimentos_preparados_rotiseria         0
articulos_limpieza_perfumeria          0
indumentaria_calzado_textiles_hogar    0
electronicos_articulos_hogar           0
otros                                  0
dtype: int64

In [29]:
# Convertir dataframe a csv
data1.to_csv("Metodo6.csv")